// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy7SvaqfNC4pfAEjABMlYbxAKszg9uj0E',
    appId: '1:81455678700:web:602fa91a67565d8c5ad1c9',
    messagingSenderId: '81455678700',
    projectId: 'mechmaster-8e431',
    authDomain: 'mechmaster-8e431.firebaseapp.com',
    storageBucket: 'mechmaster-8e431.firebasestorage.app',
    measurementId: 'G-T6TQVP4C3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJL_s7tizSRDO3MNp86lj8eMRDupCRenU',
    appId: '1:81455678700:android:4ff83d758adb3f555ad1c9',
    messagingSenderId: '81455678700',
    projectId: 'mechmaster-8e431',
    storageBucket: 'mechmaster-8e431.firebasestorage.app',
  );
}
